#Python basics

Import libraries to work with:

```import nombre_libreria as apodo``` to be used as ```apodo.method```, ```apodo.class``` or ```apodo.attribute```

```from nombre_libreria import elemento as apodo``` to be used as ```apodo.method```, ```apodo.class``` or ```apodo.attribute```





In [ ]:
import numpy as np #Librería de operaciones numéricas
import matplotlib.pyplot as plt  #Librería de graficación

For instance, compute $sin(2\pi)$:

In [ ]:
np.sin(np.pi)

1.2246467991473532e-16

Most of the models are already implemented as classes. So, a class (with arguments, attributes, and methods) is defined as:

In [ ]:
class Person():
  #__init__: método
  def __init__(self,name,age=0,nat=None): #name argumento
    self.name = name #self.age atributo
    self.age = age
    self.nat = nat
  def introduce(self,lang='en'):
    if lang == 'es':
      print('Buenas. Mi nombre es',self.name)
      print('Tengo',self.age)
      if self.nat is not None:
        print('Soy de {}'.format(self.nat))
    elif lang == 'en':
      print('Hi! My name is',self.name,'\nI am {} y/o'.format(self.age))
      if self.nat is not None:
        print('I am from {}'.format(self.nat))

p1 = Person('Mauricio',5,'FR') #Objeto
p2 = Person('Camila',4)
p3 = Person('Bryan',nat='US',age=1)

print(p1.nat)
p1.name, p1.age
p2.name, p2.age

p2.introduce()
p1.introduce('es')
p3.introduce()

FR
Hi! My name is Camila 
I am 4 y/o
Buenas. Mi nombre es Mauricio
Tengo 5
Soy de FR
Hi! My name is Bryan 
I am 1 y/o
I am from US


##Arrays
An array object represents a multidimensional, homogeneous array of fixed-size items. An associated data-type object describes the format of each element in the array (its byte-order, how many bytes it occupies in memory, whether it is an integer, a floating point number, or something else, etc.)
[numpy ndarray.](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

Some useful methods and attributes are the following:

In [ ]:
X = np.arange(-1,9,2)
print(X)
print(X.size)
print(X.shape)

[-1  1  3  5  7]
5
(5,)


In [ ]:
A = np.arange(1,13,0.5).reshape((6,4))
print(A)
print(A.size,A.shape)

[[ 1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5]
 [ 5.   5.5  6.   6.5]
 [ 7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5]
 [11.  11.5 12.  12.5]]
24 (6, 4)


In [ ]:
B = np.linspace(0,10,6)
print(B)

[ 0.  2.  4.  6.  8. 10.]


In [ ]:
Z = np.zeros((4,3,5))
Z

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
NUM_VIDEOS,TIME,ROW,COL,COLOR = 10,5,30,40,3
U = np.ones((NUM_VIDEOS,TIME,ROW,COL,COLOR))
U.shape

(10, 5, 30, 40, 3)

In [ ]:
R = np.random.normal(loc=10,scale=0.1,size=(6,6))
R

array([[10.03946913,  9.90210018,  9.91477262, 10.03375031,  9.94969246,
         9.98518912],
       [10.08903823, 10.10489901, 10.00118954,  9.963903  ,  9.81362952,
        10.12295407],
       [10.06143854,  9.91299008, 10.23846475,  9.93034539,  9.9118524 ,
         9.9259817 ],
       [ 9.89207413,  9.95662514, 10.03022034,  9.96775452, 10.08348977,
         9.91083975],
       [10.02513434,  9.98297807,  9.71656678, 10.04041106,  9.77508264,
         9.94458787],
       [ 9.98004296, 10.02446648, 10.16010786,  9.70280991,  9.92937072,
         9.8105078 ]])

##Lists:
Lists are used to store multiple items in a single variable.

In [ ]:
lista1 = ['a','b',123,p1]
print(lista1)
print(lista1[2])

lista2=[p1,p2,p3]
print(lista2)

for i in [0,1,2]:
  lista2[i].introduce()

for i in np.arange(len(lista2)):
  lista2[i].introduce()

for persona in lista2:
  persona.introduce()

for i,persona in enumerate(lista2):
  print(i)
  persona.introduce()


letras = ['a','b','c']
numeros = ['10','20','30']

for l,n,p in zip(letras,numeros,lista2):
  print(l,n)
  print(p.introduce())


['a', 'b', 123, <__main__.Person object at 0x7f04ca082290>]
123
[<__main__.Person object at 0x7f04ca082290>, <__main__.Person object at 0x7f04ca082250>, <__main__.Person object at 0x7f04ca0820d0>]
Hi! My name is Mauricio 
I am 5 y/o
I am from FR
Hi! My name is Camila 
I am 4 y/o
Hi! My name is Bryan 
I am 1 y/o
I am from US
Hi! My name is Mauricio 
I am 5 y/o
I am from FR
Hi! My name is Camila 
I am 4 y/o
Hi! My name is Bryan 
I am 1 y/o
I am from US
Hi! My name is Mauricio 
I am 5 y/o
I am from FR
Hi! My name is Camila 
I am 4 y/o
Hi! My name is Bryan 
I am 1 y/o
I am from US
0
Hi! My name is Mauricio 
I am 5 y/o
I am from FR
1
Hi! My name is Camila 
I am 4 y/o
2
Hi! My name is Bryan 
I am 1 y/o
I am from US
a 10
Hi! My name is Mauricio 
I am 5 y/o
I am from FR
None
b 20
Hi! My name is Camila 
I am 4 y/o
None
c 30
Hi! My name is Bryan 
I am 1 y/o
I am from US
None


A list comprehension embeds for loops while building lists:

In [ ]:
lista3 = []
for i in np.arange(11):
  lista3.append(i**2)
  print(lista3)

lista3 = [i**2 for i in np.arange(11)]
print(lista3)

lista3 = [i**2 for i in np.arange(11) if i**2>20]
print(lista3)

lista3 = [i**2 if i**2>20 else -10 for i in np.arange(11) ]
print(lista3)


[0]
[0, 1]
[0, 1, 4]
[0, 1, 4, 9]
[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16, 25]
[0, 1, 4, 9, 16, 25, 36]
[0, 1, 4, 9, 16, 25, 36, 49]
[0, 1, 4, 9, 16, 25, 36, 49, 64]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[25, 36, 49, 64, 81, 100]
[-10, -10, -10, -10, -10, 25, 36, 49, 64, 81, 100]


A numpy array can be built from lists of lists of lists.... of scalars.

In [ ]:
X = np.array([[5,1],[-9,3],[40,1.1],[0.5,7],[1,2]])
print(X)
print(X.shape)

[[ 5.   1. ]
 [-9.   3. ]
 [40.   1.1]
 [ 0.5  7. ]
 [ 1.   2. ]]
(5, 2)


## Dictionaries

Dictionaries are used to store data values in key:value pairs.

A dictionary is a collection which is ordered*, changeable and do not allow duplicates.

In [ ]:
P1 = {'name':'Luis',
      'age':15,
      'age':38,
}

P1['age']+=1
print(P1)

P1['lastname'] = 'Hernandez'
print(P1)

{'name': 'Luis', 'age': 39}
{'name': 'Luis', 'age': 39, 'lastname': 'Hernandez'}


##Operations

### Unary Operations

In [ ]:
x = np.arange(0,100,2)
np.exp(x),np.cos(x) #unary

(array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
        2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
        8.88611052e+06, 6.56599691e+07, 4.85165195e+08, 3.58491285e+09,
        2.64891221e+10, 1.95729609e+11, 1.44625706e+12, 1.06864746e+13,
        7.89629602e+13, 5.83461743e+14, 4.31123155e+15, 3.18559318e+16,
        2.35385267e+17, 1.73927494e+18, 1.28516001e+19, 9.49611942e+19,
        7.01673591e+20, 5.18470553e+21, 3.83100800e+22, 2.83075330e+23,
        2.09165950e+24, 1.54553894e+25, 1.14200739e+26, 8.43835667e+26,
        6.23514908e+27, 4.60718663e+28, 3.40427605e+29, 2.51543867e+30,
        1.85867175e+31, 1.37338298e+32, 1.01480039e+33, 7.49841700e+33,
        5.54062238e+34, 4.09399696e+35, 3.02507732e+36, 2.23524660e+37,
        1.65163625e+38, 1.22040329e+39, 9.01762841e+39, 6.66317622e+40,
        4.92345829e+41, 3.63797095e+42]),
 array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003,
        -0.83907153, 

### Binary Operations

In [ ]:
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x+y,x*y,x/y,x**y

(array([ 3,  4,  6, 10]),
 array([ 2,  4,  8, 16]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1,  4, 16, 64]))

In [ ]:
x = np.array([1, 2, 4, 8])
y = 3
x+y,x*y,x/y,x**y

(array([ 4,  5,  7, 11]),
 array([ 3,  6, 12, 24]),
 array([0.33333333, 0.66666667, 1.33333333, 2.66666667]),
 array([  1,   8,  64, 512]))

There is a method for concatenating two or more arrays along a given axis:

In [ ]:
X = np.arange(12).reshape(3, 4)
print('X:',X.shape)
print(X)
Y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print('Y:',Y.shape)
print(Y)

#  5 x 2
# 10 x 2
#--------
# 15 x 2

# 30 x 8
# 30 x 4
#-------
# 30 x 12

# 5 x 6 x 500
# 5 x 6 x 1000
#--------------
# 5 x 6 x 1500

Z=np.concatenate((X,Y))
print(Z.shape)
NZ=np.concatenate((X,Y),axis=1)
print(NZ.shape)

X: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Y: (3, 4)
[[2 1 4 3]
 [1 2 3 4]
 [4 3 2 1]]
(6, 4)
(3, 8)


Logical operations are also element-wise applied:

In [ ]:
X == 4

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [ ]:
X != Y

array([[ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Numpy arrays are objects with useful methods:

In [ ]:
np.sum(X)
X.sum()
X.mean()
X.var()
M=X.mean(axis=0)
print(M,M.shape)

[4. 5. 6. 7.] (4,)


##Broadcasting

This property propagates (when possible) a binary operation:

In [ ]:
a = np.arange(3).reshape(3, 1)
b = np.array([-1,0,1]).reshape(1,3)
print('a:',a.shape,type(a))
print(a)
print('b:',b.shape)
print(b)

a: (3, 1) <class 'numpy.ndarray'>
[[0]
 [1]
 [2]]
b: (1, 3)
[[-1  0  1]]


In [ ]:
C = a+b
print('C:',C.shape,type(C))
print(C)

C: (3, 3) <class 'numpy.ndarray'>
[[-1  0  1]
 [ 0  1  2]
 [ 1  2  3]]


##Indexing and slicing




In [ ]:
print(X)
print(X[1])
print(X[1,2])
print(X[1][2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
6
6


In [ ]:
print(X[:])
print(X[1:])
print(X[:1])
print(X[-2:-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[[4 5 6 7]]


In [ ]:
X[2][2]=20
print(X)
X[1]=5
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 20 11]]
[[ 0  1  2  3]
 [ 5  5  5  5]
 [ 8  9 20 11]]


[[12 12 12 12]
 [12 12 12 12]
 [ 8  9 10 11]]


[[-1  0]
 [ 8 -2]] int64
[[12 -1  0 12]
 [12  8 -2 12]
 [ 8  9 10 11]] int64


In [ ]:
L = [[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1],[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]
print(type(L))
print(L[4][1])

<class 'list'>
2


##Pointers and memory

```id()``` function gives the exact address of the  referenced object in memory

In [ ]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [ ]:
before = id(X)
X += Y
id(X) == before

True

In [ ]:
Z = np.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140445302817200
id(Z): 140445302817200


#Linear algebra

##Scalars

$x\in\mathbb{R}$

$y\in\mathbb{C}$

$z\in\{0,1\}$

In [ ]:
x = np.array(3.0)
y = np.array(2.0)


##Vectors

$\bf{x}$ $\in\mathbb{R}^N$

$\bf{y}$ $\in\mathbb{C}^N$

$\bf{z}$ $\in\{0,1\}^N$

In [ ]:
x = np.arange(4)
print(x)


[0 1 2 3]


##Matrices

$\bf{X}$ $\in\mathbb{R}^{N\times M}$

$\bf{Y}$ $\in\mathbb{C}^{N\times M}$

$\bf{Z}$ $\in\{0,1\}^{N\times M}$

In [ ]:
A = np.arange(20).reshape(5, 4)
print('A:',A.shape)

A: (5, 4)


In [ ]:
B = np.array([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(B)
print(B==B.T)

[[1 2 3]
 [2 0 4]
 [3 4 5]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


##Tensors

$\bf{X}$ $\in\mathbb{R}^{N_1\times N_2 \times N_3}$

$\bf{Y}$ $\in\mathbb{C}^{N_1\times N_2 \times N_3 \times N_4}$

$\bf{Z}$ $\in\{0,1\}^{N_1\times N_2 \times N_3 \times \dots}$

In [ ]:
X = np.arange(24).reshape(2, 3, 4)
print('X:',X.shape)
print(X)

X: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
A = np.arange(20).reshape(5, 4)
print(A)
B = A #shallow copy / copia superficial
B[2][1]= 20
print(B)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8 20 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8 20 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
import copy
A = np.arange(20).reshape(5, 4)
# Assign a copy of `A` to `B` by allocating new memory, deep copy:
B = copy.deepcopy(A)
B[2][1]= 20
print(B)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8 20 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


Sum and product by scalar sums and multiplies each array element by the given scalar (like a broadcasting):

In [ ]:
A*5
print(A*5)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]
 [80 85 90 95]]


Some operations can perform along a given axis:

In [ ]:
A.shape, A.sum()

((5, 4), 190)

In [ ]:
A_sum_axis0 = A.sum(axis=0)
print(A_sum_axis0)

[40 45 50 55]


In [ ]:
A_sum_axis1 = A.sum(axis=1)
print(A_sum_axis1)

[ 6 22 38 54 70]


In [ ]:
A.sum(axis=None) # Same as `A.sum()`

190

In [ ]:
print(A.size)
print(A.mean())
print(A.sum())
print(A.sum() / A.size)

20
9.5
190
9.5


In [ ]:
print(A)
print(A.shape[1])
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
4


(array([ 8.,  9., 10., 11.]), array([ 8.,  9., 10., 11.]))

Try this:

```
A = np.arange(20).reshape(5, 4)
A - A.mean(axis=1)
```



In [ ]:
A = np.arange(20).reshape(5, 4)
A - A.mean(axis=1)

ValueError: ignored

```keepdims=True``` avoids axis reduction:



In [ ]:
sum_A = A.sum(axis=1)
sum_A_nonred = A.sum(axis=1, keepdims=True)
print(A.shape)
print(sum_A.shape)
print(sum_A_nonred.shape)
print(A)
print(sum_A)
print(sum_A_nonred)

(5, 4)
(5,)
(5, 1)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 6 22 38 54 70]
[[ 6]
 [22]
 [38]
 [54]
 [70]]


In [ ]:
A / sum_A

ValueError: ignored

In [ ]:
P = A / sum_A_nonred
print(P)
print(P.sum(axis=1))

[[0.         0.16666667 0.33333333 0.5       ]
 [0.18181818 0.22727273 0.27272727 0.31818182]
 [0.21052632 0.23684211 0.26315789 0.28947368]
 [0.22222222 0.24074074 0.25925926 0.27777778]
 [0.22857143 0.24285714 0.25714286 0.27142857]]
[1. 1. 1. 1. 1.]


In [ ]:
print(A)
print(A.mean(axis=0,keepdims=True))
A - A.mean(axis=0,keepdims=True)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 8.  9. 10. 11.]]


array([[-8., -8., -8., -8.],
       [-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

## Dot product

$\bf{x}^\top\bf{y}=<\bf{x},\bf{y}>$$=\sum_{i}{x_iy_i}$

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])
(x*y).sum()
np.dot(x,y)
x.dot(y)

32

```dot()``` also performs matrix-vector products:

In [ ]:
T=np.arange(15).reshape((5,3))
T.dot(x)

array([ 8, 26, 44, 62, 80])

```dot()``` also performs matrix-matrix products:

In [ ]:
S=np.arange(15).reshape((3,5))
S.dot(T)

array([[ 90, 100, 110],
       [240, 275, 310],
       [390, 450, 510]])

## Norms

L2 norm:
$||\bf{x}$$||_2=(\sum_{i}{x_i^2})^{1/2}$

In [ ]:
u = np.array([3, -4])
N= np.sqrt(np.sum(u**2))
print(N)
np.linalg.norm(u)

5.0


5.0

L1 norm:
$||\bf{x}$$||_1=\sum_{i}{|x_i|}$

In [ ]:
r = np.linalg.norm(u,1)
print(r)


7.0


Lp norm:
$||\bf{x}$$||_p=(\sum_{i}{|x_i|^p})^{1/p}$

In [ ]:
u = np.array([-0.1,5e-3,1/12])
n = np.linalg.norm(u,np.infty)
print(n)

0.1


#Probabilities

## Joint Probability

Given any values $a$ and $b$, the joint probability $P(A = a; B = b)$ lets us answer, what is the probability that $A = a$ and $B = b$ **simultaneously**?

## Marginalization
One important operation that we need is marginalization. It is the operation of determining $P(B)$ from $P(A; B)$. We can see that the probability of $B$ amounts to accounting for all possible choices of $A$ and aggregating the joint probabilities over all of them:

$P(B) = \sum_A P(A; B)$

$A = \{Ma,Pe,Ba\}$

$B = \{Alta,Baja\}$

$P(B=Alta)=P(Ma;Alta) + P(Ba;Alta) + P(Pe;Alta)$

$P(B=Baja)=P(Ma;Baja) + P(Ba;Baja) + P(Pe;Baja)$

$P(B=Baja)+P(B=Alta)=1$

which is also known as **the sum rule**. The probability or distribution as a result of marginalization
is called a **marginal probability** or a **marginal distribution**.

## Conditional Probability
Note that for any values $a$ and $b$:

$P(A = a; B = b) \leq P(A = a)$.

This has to be the case, since for $A = a$ and $B = b$ to happen, $A = a$ has to happen and $B = b$ also has to happen (and vice versa). Thus, $A = a$ and $B = b$ cannot be more likely than $A = a$ or $B = b$ individually.

This brings us to an interesting ratio:

$0 \leq \frac{P(A = a; B = b)}{P(A = a)} \leq 1$

We call this ratio a **conditional probability** and denote it by

$P(B = b | A = a)$

It is the probability of $B = b$, provided that $A = a$ has occurred.

$P(B=Alta|A=Ba)=\frac{P(B=Alta,A=Ba)}{P(A=Ba)}$

$P(B=Alta,A=Ba) = P(B=Alta|A=Ba)P(A=Ba)$


## Bayes' theorem

Using the definition of conditional probabilities, we can derive one of the most useful and celebrated equations in statistics: Bayes' theorem. It goes as follows:

By construction, we have the **multiplication rule** that

$P(A; B) = P(B | A)P(A)$

By symmetry, this also holds for

$P(A; B) = P(A | B)P(B)$

Solving for one of the conditional variables we get
$P(A | B) = \frac{P(B | A)P(A)}{P(B)}$


$P(A=spam | B) = \frac{0.7 * 0.1 }{0.754}= \frac{0.07}{0.754}$

$P(A=no spam | B) = \frac{0.005 * 0.9}{0.754} = \frac{0.0045}{0.754}$


## Example
Assume that a doctor administers a cancer test to a patient. This test is fairly accurate and it fails only with 1% probability if the patient is healthy but reporting
him as diseased. Moreover, it never fails to detect cancer if the patient actually has it. We use $D_1$ to
indicate the diagnosis (1 if positive and 0 if negative) and $H$ to denote the cancer status (1 if positive
and 0 if negative). Such conditional probabilities are as follows:

$P(D_1=1|H=1)=1$

$P(D_1=0|H=1)=0$

$P(D_1=1|H=0)=0.01$

$P(D_1=0|H=0)=0.99$


Let us work out the probability of the patient having cancer if the test comes back positive, i.e., $P(H = 1 | D_1 = 1)$. Obviously this is going to depend on how common the disease is, since it affects the number of false alarms. Assume that the population is quite healthy, e.g., $P(H = 1) = 0.0015$.

To apply Bayes' theorem, we need to apply marginalization and the multiplication rule to determine

$P(D_1)=P(D_1;H=0)+P(D_1;H=1)$

$P(D_1=0)=P(D_1=0|H=0)P(H=0)+P(D_1=0|H=1)P(H=1)$

$P(D_1=1)=P(D_1=1|H=0)P(H=0)+P(D_1=1|H=1)P(H=1)$

In [ ]:
# Cond 2 x 2
cond = np.zeros((2,2)) #D_1 | H
cond[0][0],cond[0][1],cond[1][0],cond[1][1] = 0.99,0,0.01,1
print('Conditional:\n',cond)
print(cond.sum(axis=0))

# Marginal / a-priori
prior = np.zeros((2,)) # H
prior[0],prior[1]=1-0.0015,0.0015
print('Prior:',prior,prior.sum())

#Conj 2 x 2
conj = np.zeros((2,2)) #D_1 , H
conj[0][0],conj[0][1],conj[1][0],conj[1][1]=cond[0][0]*prior[0],cond[0][1]*prior[1],cond[1][0]*prior[0],cond[1][1]*prior[1]
print('Joint\t:\n',conj) #\t tab , \n enter
print(conj.sum())

#{P(D1)}
evidence = conj.sum(axis=1)
prior=prior.reshape((1,2))
joint = 0
print('Joint\t:\n',joint)


post = np.zeros((2,2))
print('Posterior:\n',post)

Conditional:
 [[0.99 0.  ]
 [0.01 1.  ]]
[1. 1.]
Prior: [0.9985 0.0015] 1.0
Joint	:
 [[0.988515 0.      ]
 [0.009985 0.0015  ]]
1.0
Joint	:
 0
Posterior:
 [[0. 0.]
 [0. 0.]]


There is only a 13.06% chance that the patient actually has cancer, despite using a very accurate test.

What should a patient do upon receiving such terrifying news? Likely, the patient would ask the physician to administer another test to get clarity. The second test has different characteristics and it is not as good as the first one:

$P(D_2=1|H=1)=0.98$

$P(D_2=0|H=1)=0.02$

$P(D_2=1|H=0)=0.03$

$P(D_2=0|H=0)=0.97$

Unfortunately, the second test comes back positive, too. Let us work out the requisite probabilities to invoke Bayes' theorem by assuming the conditional independence:

$P(D_1=1,D_2=1|H=0)=??$

$P(D_1=1,D_2=1|H=1)=??$


In [ ]:
#Compute P(D1;D2|H): P[0,0,0]


Now we can apply marginalization and the multiplication rule to obtain the joint diagnosis probability:

$P(D_1 = 1; D_2 = 1)=??$

In [ ]:
#Compute P(D1;D2):


In the end, the probability of the patient having cancer given both positive tests is

$P(H = 1 | D_1 = 1; D_2 = 1)=??$

In [ ]:
# Compute P(H = 1 | D_1 = 1; D_2 = 1)


## Gaussian distributions

In [ ]:
from scipy.io import loadmat

data = loadmat('data.mat')
print(data.keys())
X = data['X']
print(X.shape,type(X),X.dtype)

plt.scatter(X[:,0],X[:,1])
plt.axis('square')
plt.xlim([-6,6])
plt.ylim([-6,6])
plt.grid()
plt.show()

In [ ]:
#Cálculo de medias:
m = np.mean(X,axis=0)
print(m)
m = X.mean(axis=0)
print(m)

#Cálculo de covarianza:

#Valores y vectores propios: C@v = lambda*v


In [ ]:
from scipy.stats import multivariate_normal

#Probabilidades gaussianas:

#Malla de valores:


#Probabilidad sobre la malla:

plt.scatter(X[:,0],X[:,1])

plt.axis('square')
plt.xlim([-6,6])
plt.ylim([-6,6])
plt.grid()
plt.show()

R = np.corrcoef(X,rowvar=False)
print(R)